version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: source/services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: source/services/Basket/Basket.API/Dockerfile

  theshop.razorweb:
    image: ${DOCKER_REGISTRY-}theshoprazorweb
    build:
      context: .
      dockerfile: source/webapps/TheShop.RazorWeb/Dockerfile

  theshop.webstatus:
    image: ${DOCKER_REGISTRY-}theshopwebstatus
    build:
      context: .
      dockerfile: source/webapps/TheShop.WebStatus/Dockerfile

volumes:
  mongo_data:
